INSERT INTO OPERATION_TYPE (description) VALUES ('COMPRA A VISTA')
INSERT INTO OPERATION_TYPE (description) VALUES ('COMPRA PARCELADA')
INSERT INTO OPERATION_TYPE (description) VALUES ('SAQUE')
INSERT INTO OPERATION_TYPE (description) VALUES ('PAGAMENTO')